name: Bug report
description: Create a report to help us improve
labels: 'bug'

body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue make sure you are running the latest build of Leaf and checked for duplicate issues!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  
  - type: textarea
    attributes:
      label: What behaviour is observed?
      description: A clear and concise description of what the behavior is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce this behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin list
      description: This can be found by running `/pl`
    validations:
      required: true

  - type: input
    attributes:
      label: Leaf Version
      description: What version of Leaf are you running? (`/version`)
    validations:
      required: true

  - type: input
    attributes:
      label: Error log (if applicable)
      description: If you are reporting a console error, upload any relevant log excerpts to either https://mclo.gs or https://gist.github.com, save and the paste the link in this box.

  - type: input
    attributes:
      label: Configuration
      description: Link of your Leaf & Gale config files, upload any relevant log excerpts to either https://paste.gg or https://gist.github.com, save and the paste the link in this box.
