name: Automatically update Gale commit hash
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Leaf Repository
        uses: actions/checkout@v3
        with:
          path: 'Leaf'
          token: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Checkout Gale Repository
        uses: actions/checkout@v3
        with:
          path: 'Gale'
          repository: "GaleMC/Gale"
          token: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Get Gale Latest Commit Hash
        id: galeRef
        run: |
          ls
          cd Gale
          echo "::set-output name=galeRef::$(git rev-parse HEAD)"
          cd ..
         
      - name: Update galeRef in Leaf 
        run: |
          cd Leaf
          sed -i "s/\(galeRef\s*=\s*\).*/\1$PAPER_REF/" gradle.properties
        env:
          PAPER_REF: ${{ steps.galeRef.outputs.galeRef }}
      - name: Check for changes and Write to repository
        run: |
          cd Leaf
          if ! git diff --quiet; then
            git add gradle.properties
            git config user.name "HaHaWTH"
            git config user.email HaHaWTH@users.noreply.github.com
            git commit -m "Updated Upstream (Gale)"
            git push
          else
            echo "No changes to commit."
          fi
