name: Build Leaf 1.21.4
on:
  push:
    branches: [ "ver/1.21.4" ]

jobs:
  setup:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    outputs:
      build_number: ${{ github.run_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Apply patches
        run: |
          ./gradlew -Dorg.gradle.jvmargs="${GRAALVM_ARGS}" \
          -Dorg.gradle.parallel=true \
          -Dorg.gradle.caching=true \
          applyAllPatches --stacktrace --no-daemon
        env:
          GRAALVM_ARGS: "-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector"
      - name: Cache patched sources
        uses: actions/cache@v4
        with:
          path: |
            ./*/src
            ./*/build
            ./.gradle
          key: ${{ runner.os }}-patched-${{ github.sha }}

  build-mojmap:
    needs: setup
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle
      - name: Restore patched sources
        uses: actions/cache@v3
        with:
          path: |
            ./*/src
            ./*/build
            ./.gradle
          key: ${{ runner.os }}-patched-${{ github.sha }}
      - name: Create MojmapPaperclipJar
        run: |
          ./gradlew -Dorg.gradle.jvmargs="${GRAALVM_ARGS}" \
          -Dorg.gradle.parallel=true \
          -Dorg.gradle.caching=true \
          createMojmapPaperclipJar --stacktrace --no-daemon
        env:
          GRAALVM_ARGS: "-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector"
      - name: Rename Mojmap Jar
        run: |
          mv leaf-server/build/libs/leaf-paperclip-1.21.4-R0.1-SNAPSHOT-mojmap.jar ./leaf-1.21.4-${{ needs.setup.outputs.build_number }}-mojmap.jar
      - name: Upload Mojmap jar
        uses: actions/upload-artifact@v3
        with:
          name: leaf-mojmap-jar
          path: ./leaf-1.21.4-${{ needs.setup.outputs.build_number }}-mojmap.jar

  build-reobf:
    needs: setup
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle
      - name: Restore patched sources
        uses: actions/cache@v4
        with:
          path: |
            ./*/src
            ./*/build
            ./.gradle
          key: ${{ runner.os }}-patched-${{ github.sha }}
      - name: Create ReobfPaperclipJar
        run: |
          ./gradlew -Dorg.gradle.jvmargs="${GRAALVM_ARGS}" \
          -Dorg.gradle.parallel=true \
          -Dorg.gradle.caching=true \
          -Dpaperweight.debug=true createReobfPaperclipJar --stacktrace --no-daemon
        env:
          GRAALVM_ARGS: "-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector"
      - name: Rename Reobf Jar
        run: |
          mv leaf-server/build/libs/leaf-paperclip-1.21.4-R0.1-SNAPSHOT-reobf.jar ./leaf-1.21.4-${{ needs.setup.outputs.build_number }}-reobf.jar
      - name: Upload Reobf jar
        uses: actions/upload-artifact@v4
        with:
          name: leaf-reobf-jar
          path: ./leaf-1.21.4-${{ needs.setup.outputs.build_number }}-reobf.jar

  publish:
    needs: [setup, build-mojmap, build-reobf]
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle
      - name: Restore patched sources
        uses: actions/cache@v4
        with:
          path: |
            ./*/src
            ./*/build
            ./.gradle
          key: ${{ runner.os }}-patched-${{ github.sha }}
      - name: Download all jars
        uses: actions/download-artifact@v4
      - name: Move jars to expected locations
        run: |
          mkdir -p ./artifacts
          mv ./leaf-mojmap-jar/leaf-1.21.4-${{ needs.setup.outputs.build_number }}-mojmap.jar ./leaf-1.21.4-${{ needs.setup.outputs.build_number }}-mojmap.jar
          mv ./leaf-reobf-jar/leaf-1.21.4-${{ needs.setup.outputs.build_number }}-reobf.jar ./leaf-1.21.4-${{ needs.setup.outputs.build_number }}-reobf.jar
          cp ./leaf-1.21.4-${{ needs.setup.outputs.build_number }}-mojmap.jar ./leaf-1.21.4-${{ needs.setup.outputs.build_number }}.jar
      - name: Publish API
        continue-on-error: true
        run: |
          echo "REPO_USER=${{ secrets.REPO_USER }}" >> $GITHUB_ENV
          export REPO_USER=${{ secrets.REPO_USER }}
          echo "REPO_PASSWORD=${{ secrets.REPO_PASSWORD }}" >> $GITHUB_ENV
          export REPO_PASSWORD=${{ secrets.REPO_PASSWORD }}
          ./gradlew -Dorg.gradle.parallel=true -Dorg.gradle.caching=true publish
          # Uncomment when ready to implement:
          # ./gradlew publishDevBundlePublicationToLeafRepository -PpublishDevBundle=true
      - name: Upload Leaf as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Leaf 1.21.4
          path: ./leaf-1.21.4-*.jar
      - name: Release Leaf
        uses: softprops/action-gh-release@v2
        with:
          name: "Leaf 1.21.4"
          tag_name: "ver-1.21.4"
          files: "./leaf-1.21.4-${{ needs.setup.outputs.build_number }}.jar"
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
