name: Build LeafPrismarine-1.19.2
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@master
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace
      - name: Create ReobfPaperclipJar
        run: ./gradlew createReobfPaperclipJar --stacktrace
      - name: Rename Paperclip Jar
        run: mv build/libs/leafprismarine-paperclip-1.19.2-R0.1-SNAPSHOT-reobf.jar ./leafprismarine-1.19.2.jar
      - name: Upload LeafPrismarine
        uses: actions/upload-artifact@v3
        with:
          name: LeafPrismarine-1.19.2
          path: ./leafprismarine-1.19.2.jar
